openapi: 3.0.3
info:
  title: Tenant Management Micro Service
  description: defines the persistence operations for the tenant
  version: '{{version}}'
  contact:
    name: API Support
    url: 'http://www.example.com/support'
    email: support@example.com
  termsOfService: 'http://swagger.io/terms/'
  x-api-id: an x-api-id
  x-summary: an x-summary
servers:
  - url: '/tenant-management/{{version}}'
    description: This service is tenant manager
security:
  - bearerAuth: []
tags:
  - name: tenant
    description: Everything about your Tenants
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /tenants:
    parameters:
      - $ref: '#/components/parameters/CorrelationIdHeader'
      - $ref: '#/components/parameters/IpAddress'
    post:
      tags:
        - tenant
      summary: Create a new tenant
      operationId: createTenant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantSeed'
        required: true
      responses:
        '200':
          description: Tenant created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Tenant already exists
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /tenants/{tenantId}:
    parameters:
      - $ref: '#/components/parameters/CorrelationIdHeader'
      - $ref: '#/components/parameters/IpAddress'
      - name: tenantId
        in: path
        description: the tenant id
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - tenant
      summary: Get a tenant
      operationId: getTenant
      responses:
        '200':
          description: the tenant corresponding to the tenant id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Tenant not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    post:
      tags:
        - tenant
      summary: Updates a tenant
      operationId: updateTenant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantDelta'
        required: true
      responses:
        '200':
          description: the newly updated tenant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Tenant not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    delete:
      tags:
        - tenant
      summary: Deletes a tenant
      operationId: deleteTenant
      responses:
        '204':
          description: Tenant Deleted
        '404':
          description: Tenant not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /tenants/selfcareId/{selfcareId}:
    parameters:
      - $ref: '#/components/parameters/CorrelationIdHeader'
      - $ref: '#/components/parameters/IpAddress'
      - name: selfcareId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - tenant
      summary: Get a tenant by selfcareId
      operationId: getTenantBySelfcareId
      responses:
        '200':
          description: the tenant corresponding to the selfcareId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Tenant not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /tenants/{tenantId}/attributes:
    parameters:
      - $ref: '#/components/parameters/CorrelationIdHeader'
      - $ref: '#/components/parameters/IpAddress'
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      tags:
        - attributes
      summary: Adds an attribute to a tenant
      operationId: addTenantAttribute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantAttribute'
        required: true
      responses:
        '200':
          description: the newly updated tenant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Attribute not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Attribute already exists
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /tenants/{tenantId}/attributes/{attributeId}:
    parameters:
      - $ref: '#/components/parameters/CorrelationIdHeader'
      - $ref: '#/components/parameters/IpAddress'
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: attributeId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - attributes
      summary: Retrieves an attribute within a tenant
      operationId: getTenantAttribute
      responses:
        '200':
          description: Tenant attribute
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantAttribute'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Tenant or Attribute not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    post:
      tags:
        - attributes
      summary: Updates an attribute within a tenant
      operationId: updateTenantAttribute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantAttribute'
        required: true
      responses:
        '200':
          description: the newly updated tenant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Tenant or Attribute not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /tenants/origin/{origin}/code/{code}:
    parameters:
      - $ref: '#/components/parameters/CorrelationIdHeader'
      - $ref: '#/components/parameters/IpAddress'
      - name: origin
        in: path
        description: the origin of the external id code
        required: true
        schema:
          type: string
      - name: code
        in: path
        description: the external id code
        required: true
        schema:
          type: string
    get:
      tags:
        - tenant
      summary: Get a tenant
      operationId: getTenantByExternalId
      responses:
        '200':
          description: the tenant corresponding to the external id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Tenant not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  parameters:
    CorrelationIdHeader:
      in: header
      name: X-Correlation-Id
      required: true
      schema:
        type: string
    IpAddress:
      in: header
      name: X-Forwarded-For
      schema:
        type: string
  schemas:
    Problem:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
        correlationId:
          description: Unique identifier of the request
          example: '53af4f2d-0c87-41ef-a645-b726a821852b'
          maxLength: 64
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
        errors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ProblemError'
      additionalProperties: false
      required:
        - type
        - status
        - title
        - errors
    ProblemError:
      properties:
        code:
          description: Internal code of the error
          example: 123-4567
          minLength: 8
          maxLength: 8
          pattern: '^[0-9]{3}-[0-9]{4}$'
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
      required:
        - code
        - detail
    TenantAttribute:
      type: object
      properties:
        declared:
          $ref: '#/components/schemas/DeclaredTenantAttribute'
        certified:
          $ref: '#/components/schemas/CertifiedTenantAttribute'
        verified:
          $ref: '#/components/schemas/VerifiedTenantAttribute'
    DeclaredTenantAttribute:
      type: object
      properties:
        id:
          type: string
          format: uuid
        assignmentTimestamp:
          type: string
          format: date-time
        revocationTimestamp:
          type: string
          format: date-time
      required:
        - id
        - assignmentTimestamp
    CertifiedTenantAttribute:
      type: object
      properties:
        id:
          type: string
          format: uuid
        assignmentTimestamp:
          type: string
          format: date-time
        revocationTimestamp:
          type: string
          format: date-time
      required:
        - id
        - assignmentTimestamp
    VerifiedTenantAttribute:
      type: object
      properties:
        id:
          type: string
          format: uuid
        assignmentTimestamp:
          type: string
          format: date-time
        verifiedBy:
          type: array
          items:
            $ref: '#/components/schemas/TenantVerifier'
        revokedBy:
          type: array
          items:
            $ref: '#/components/schemas/TenantRevoker'
      required:
        - id
        - assignmentTimestamp
        - verifiedBy
        - revokedBy
    TenantFeature:
      type: object
      properties:
        certifier:
          $ref: '#/components/schemas/Certifier'
    Certifier:
      description: Certifier Tenant Feature
      type: object
      properties:
        certifierId:
          type: string
      required:
        - certifierId
    TenantVerifier:
      type: object
      properties:
        id:
          type: string
          format: uuid
        verificationDate:
          type: string
          format: date-time
        expirationDate:
          type: string
          format: date-time
        extensionDate:
          type: string
          format: date-time
      required:
        - id
        - verificationDate
    TenantRevoker:
      type: object
      properties:
        id:
          type: string
          format: uuid
        verificationDate:
          type: string
          format: date-time
        expirationDate:
          type: string
          format: date-time
        extensionDate:
          type: string
          format: date-time
        revocationDate:
          type: string
          format: date-time
      required:
        - id
        - verificationDate
        - revocationDate
    Tenant:
      description: Tenant model
      type: object
      properties:
        id:
          type: string
          format: uuid
        kind:
          $ref: '#/components/schemas/TenantKind'
        selfcareId:
          type: string
        externalId:
          $ref: '#/components/schemas/ExternalId'
        features:
          type: array
          items:
            $ref: '#/components/schemas/TenantFeature'
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/TenantAttribute'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        mails:
          type: array
          items:
            $ref: '#/components/schemas/Mail'
        name:
          type: string
      required:
        - id
        - certifier
        - externalId
        - features
        - attributes
        - createdAt
        - mails
        - name
    MailSeed:
      description: A specific kind of mail
      type: object
      properties:
        kind:
          $ref: '#/components/schemas/MailKind'
        address:
          type: string
        description:
          type: string
      required:
        - kind
        - address
    Mail:
      description: A specific kind of mail
      type: object
      properties:
        kind:
          $ref: '#/components/schemas/MailKind'
        address:
          type: string
        createdAt:
          type: string
          format: date-time
        description:
          type: string
      required:
        - kind
        - address
        - createdAt
    TenantKind:
      type: string
      enum:
        - PA
        - PRIVATE
        - GSP
    MailKind:
      type: string
      enum:
        - CONTACT_EMAIL
    ExternalId:
      properties:
        origin:
          type: string
        value:
          type: string
      required:
        - origin
        - value
    TenantSeed:
      description: Tenant Seed model
      type: object
      properties:
        id:
          type: string
          format: uuid
        externalId:
          $ref: '#/components/schemas/ExternalId'
        features:
          type: array
          items:
            $ref: '#/components/schemas/TenantFeature'
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/TenantAttribute'
        name:
          type: string
        kind:
          $ref: '#/components/schemas/TenantKind'
      required:
        - externalId
        - features
        - attributes
        - name
        - kind
    TenantDelta:
      description: Tenant Delta model
      type: object
      properties:
        selfcareId:
          type: string
        features:
          type: array
          items:
            $ref: '#/components/schemas/TenantFeature'
        mails:
          type: array
          items:
            $ref: '#/components/schemas/MailSeed'
        kind:
          $ref: '#/components/schemas/TenantKind'    
      required:
        - features
        - mails
        - kind
  securitySchemes:
    bearerAuth:
      type: http
      description: 'A bearer token in the format of a JWS and conformed to the specifications included in [RFC8725](https://tools.ietf.org/html/RFC8725).'
      scheme: bearer
      bearerFormat: JWT d'Interoperabilità di AgID (default)
